# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0010_auto_20190421_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
