# Generated by Django 2.2 on 2019-09-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0012_auto_20190421_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['number']},
        ),
    ]
